---
driver:
  name: vagrant
  ssh:
    insert_key: false
  # network:
  # - ["forwarded_port", {guest: 22,   host: 2200, auto_correct: true}]
  # - ["forwarded_port", {guest: 80,   host: 8080, auto_correct: true}]
  # - ["forwarded_port", {guest: 443,   host: 8443, auto_correct: true}]
  cachier: true
  customize:
    memory: 4096

driver_config:
  require_chef_omnibus: 12.9.41

provisioner:
  require_chef_omnibus: true
  name: chef_zero
  log_level: info
  environments_path: test/integration/environments
  attributes:
    openssh:
      server:
        permit_root_login: 'yes'
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true

platforms:
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04
    run_list:
    - recipe[apt]
  # - name: centos-7.3
  #   run_list:
  #   - recipe[yum]
  # - name: debian-7.8
  #   run_list:
  #   - recipe[apt]

suites:
  - name: default
    sudo: true
    run_list:
    - recipe[test::default]
  - name: cloud
    run_list:
    - recipe[test::cloud]
  - name: email
    run_list:
    - recipe[test::email]
  - name: multimedia
    run_list:
    - recipe[test::multimedia]
  - name: web
    run_list:
    - recipe[test::web]
