# encoding: UTF-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

name 'paramount'
maintainer 'Michael Burns'
maintainer_email 'michael@mirwin.net'
license 'Apache 2.0'
description 'Installs/Configures a complete online software stack'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.1.1'

source_url 'https://github.com/mburns/cookbook-paramount' if respond_to?(:source_url)
issues_url 'https://github.com/mburns/cookbook-paramount/issues' if respond_to?(:issues_url)

depends 'aide'
depends 'automatic_updates'
depends 'apt'
depends 'ark'
depends 'build-essential'
depends 'chef-sugar'
depends 'chef-vault'
depends 'clamav'
depends 'couchpotato'
depends 'database'
depends 'djbdns'
depends 'dovecot'
depends 'dspam'
depends 'encfs'
depends 'fail2ban'
depends 'firewall'
depends 'hostsfile'
depends 'java'
depends 'ldap'
depends 'locales'
depends 'mosh'
depends 'nginx'
depends 'ntp'
depends 'ohai'
depends 'opendkim'
depends 'openldap'
depends 'openssh'
depends 'openssl'
depends 'owncloud'
depends 'packages'
depends 'php-fpm'
depends 'plexapp'
depends 'postfix-full'
depends 'postfixadmin'
depends 'prosody'
depends 'rkhunter'
depends 'roundcube'
depends 'rsyslog'
depends 'runit'
depends 'sabnzbd'
depends 'sickbeard'
depends 'onddo-spamassassin'
depends 'ssl_certificate'
depends 'sudo'
depends 'sysctl'
depends 'ubuntu'
depends 'users'
depends 'yum'
depends 'yum-epel'
