# -*- mode: ruby -*-
# vi: set ft=ruby :

name 'paramount'
maintainer 'Michael Burns'
maintainer_email 'michael@mirwin.net'
license 'Apache-2.0'
description 'Installs/Configures a complete online software stack'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
chef_version '>= 12.15.19' if respond_to?(:chef_version)

version begin
  IO.read(File.join(File.dirname(__FILE__), 'VERSION'))
rescue StandardError
  '0.2.0'
end

source_url 'https://github.com/mburns/cookbook-paramount' if respond_to?(:source_url)
issues_url 'https://github.com/mburns/cookbook-paramount/issues' if respond_to?(:issues_url)

supports 'centos', '>= 7'
supports 'debian', '>= 8'
supports 'fedora', '>= 27'
supports 'ubuntu', '>= 14.04'

recipe 'paramount::default', 'Includes Security and System configuration'
recipe 'paramount::cloud', 'Various cloud-based tools'
recipe 'paramount::email', 'Builds a full email stack (SMTP, IMAP, POP)'
recipe 'paramount::security', 'Hardens your host system'
recipe 'paramount::system', 'Configures basic system requirements'
recipe 'paramount::web', 'Builds a web host'

depends 'aide'
depends 'automatic_updates'
depends 'apt'
depends 'ark'
depends 'build-essential'
depends 'chef-client'
depends 'chef_client_updater'
depends 'chef-sugar'
# depends 'chef-vault'
depends 'clamav'
depends 'collectd'
depends 'couchpotato'
depends 'djbdns'
depends 'dovecot'
depends 'dspam'
depends 'elasticsearch'
depends 'encrypted_attributes'
depends 'fail2ban'
depends 'firewall'
depends 'hostsfile'
depends 'java'
depends 'kibana_lwrp'
depends 'locales'
depends 'mosh'
depends 'nginx'
depends 'ntp'
depends 'ohai'
depends 'onddo-spamassassin'
depends 'opendkim'
depends 'openldap'
depends 'openssh'
depends 'openssl'
# depends 'owncloud'
depends 'packages'
depends 'php-fpm'
depends 'plexapp'
depends 'poise-service'
depends 'postfix'
depends 'postgresql'
# depends 'postfixadmin'
depends 'prosody'
depends 'rkhunter'
# depends 'roundcube'
depends 'rsyslog'
depends 'runit'
depends 'sabnzbd'
depends 'selinux'
depends 'sickbeard'
depends 'ssl_certificate'
depends 'sudo'
# depends 'sysctl'
depends 'ubuntu'
depends 'users'
depends 'yum'
depends 'yum-epel'
